version: "3.9"
services:
  nginx:
    container_name: jira-nginx
    image: nginx:1.25.4
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./resources/static:/opt/jirarush/resources/static:ro
    depends_on:
      - app
    restart: always

  app:
    container_name: jira-app
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/jira
      - SPRING_DATASOURCE_USERNAME=jira
      - SPRING_DATASOURCE_PASSWORD=JiraRush
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=jira4jr@gmail.com
      - SPRING_MAIL_PASSWORD=zdfzsrqvgimldzyj
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always

  db:
    container_name: jira-db
    image: postgres:15
    environment:
      - POSTGRES_DB=jira
      - POSTGRES_USER=jira
      - POSTGRES_PASSWORD=JiraRush
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jira -d jira"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: