spring:
  datasource:
    url: jdbc:postgresql://db:5432/jira
    username: jira
    password: JiraRush
  config:
    import:
      - optional:file:./config/application-security.yml

server:
  port: 8080

logging:
  level:
    com.javarush.jira: INFO